<?php

namespace App\Models;

use App\Services\AuditLogger;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Facades\Storage;
use Spatie\Tags\HasTags;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Carbon;

class Asset extends Model
{
    use HasTags;

    private const DISK = 'private';

    protected $fillable = [
        'disk',
        'file_name',
        'file_type',
        'file_size',
        'mime_type',
        'extension',
        'path',
    ];

    protected static function boot(): void
    {
        //Track Our Changes
        static::updating(static function (self $asset) {
            $original = $asset->getOriginal();
            $updated = $asset->getAttributes();
            $updatedDifference = array_diff_assoc($updated, $original);
            $originalDifference = array_diff_assoc($original, $updated);
            AuditLogger::log('updated_asset', $asset, [
                'original' => $originalDifference,
                'updated' => $updatedDifference
            ]);

            //Create revision folder path
            $revisionPath = dirname($asset->path) . '/' . pathinfo($asset->file_name, PATHINFO_FILENAME) . '-revisions';
            $storage = Storage::disk(self::DISK);

            //Create revisions directory if it doesn't exist
            if (!$storage->exists($revisionPath)) {
                $storage->makeDirectory($revisionPath);
            }

            //Copy current file to revisions directory
            $revisionFileName = $asset->file_name . '_rev_' . time() . '.' . $asset->extension;
            $revisionFilePath = $revisionPath . '/' . $revisionFileName;

            if ($storage->exists($asset->path)) {
                $storage->copy($asset->path, $revisionFilePath);
            }

            //Create revision record
            $revision = new AssetRevision();
            $revision->asset_id = $asset->id;
            $revision->user_id = auth()->id() ?? null;
            $revision->file_name = $original['file_name'];
            $revision->file_type = $original['file_type'];
            $revision->file_size = $original['file_size'];
            $revision->mime_type = $original['mime_type'];
            $revision->extension = $original['extension'];
            $revision->path = $revisionFilePath;
            $revision->directory_id = $original['directory_id'];
            $revision->save();
        });

        static::updated(static function (self $asset) {
            if ($asset->isDirty('file_name')) {
                self::updateAssetStorage($asset, $asset->file_name);
            }
        });

        static::deleted(static function (self $asset) {
            self::deleteAssetFile($asset);

            //Track When Deleted.
            AuditLogger::log('deleted_asset', $asset, ['asset' => $asset]);
        });

        static::created(static function (self $asset) {
            AuditLogger::log('created_asset', $asset, ['asset' => $asset]);
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    public static function deleteAssetFile(self $asset): void
    {
        Storage::disk(self::DISK)->delete($asset->path);
    }

    public function getPreviewUrlAttribute(): string
    {
        return URL::temporarySignedRoute(
            'files.preview',
            Carbon::now()->addMinutes(5), // expires in 15 minutes
            ['asset' => $this->id]
        );
    }

    public static function updateAssetStorage(self $asset, $newFileName = null): void
    {
        //We want file name to be optional, this allows for processing files faster.
        if ($newFileName === null) {
            $newFileName = $asset->file_name;
        }
        $storage = Storage::disk(self::DISK);

        $pathArray = [];
        $currentDirectory = $asset->directory;
        if ($currentDirectory) {
            $directory = $currentDirectory;
            while ($directory) {
                $pathArray[] = $directory->name;
                $directory = $directory->parent;
            }
        }
        $path = implode(DIRECTORY_SEPARATOR, array_reverse($pathArray)) . DIRECTORY_SEPARATOR;

        $newPath = $path . $newFileName . '.' . $asset->extension;
        if ($storage->exists($asset->path)) {
            $storage->move($asset->path, $newPath);
            $asset->path = $newPath;
            $asset->saveQuietly();
        }
    }

    public function comments(): HasMany
    {
        return $this->hasMany(AssetComment::class);
    }

    public function directory(): BelongsTo
    {
        return $this->belongsTo(Directory::class);
    }

    public function properties(): HasMany
    {
        return $this->hasMany(AssetProperty::class);
    }

    public function revisions(): HasMany
    {
        return $this->hasMany(AssetRevision::class);
    }

    public function latestRevision(): HasOne
    {
        return $this->hasOne(AssetRevision::class)->latestOfMany('revision_number');
    }
}
