<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Storage;
use Spatie\Tags\HasTags;

class Asset extends Model
{
    use HasTags;

    protected $fillable = [
        'disk',
        'file_name',
        'file_type',
        'file_size',
        'mime_type',
        'extension',
        'path',
    ];

    public static function deleteAssetFile(self $asset): void
    {
        Storage::delete($asset->path);
    }

    public static function updateAssetStorage(self $asset, $newFileName = null): void
    {
        //We want file name to be optional, this allows for processing files faster.
        if ($newFileName === null) {
            $newFileName = $asset->file_name;
        }
        $storage = Storage::disk('public');

        $pathArray = [];
        $currentDirectory = $asset->directory;
        if ($currentDirectory) {
            $directory = $currentDirectory;
            while ($directory) {
                $pathArray[] = $directory->name;
                $directory = $directory->parent;
            }
        }
        $path = implode(DIRECTORY_SEPARATOR, array_reverse($pathArray)) . DIRECTORY_SEPARATOR;

        $newPath = $path . $newFileName . '.' . $asset->extension;
        if ($storage->exists($asset->path)) {
            $storage->move($asset->path, $newPath);
            $asset->path = $newPath;
            $asset->saveQuietly();
        }
    }

    protected static function boot(): void
    {
        static::updated(static function (self $asset) {
            if ($asset->isDirty('file_name')) {
                self::updateAssetStorage($asset, $asset->file_name);
            }
        });

        static::deleted(static function (self $asset) {
            self::deleteAssetFile($asset);
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }


    public function comments(): HasMany
    {
        return $this->hasMany(AssetComment::class);
    }

    public function directory(): BelongsTo
    {
        return $this->belongsTo(Directory::class);
    }

    public function properties(): HasMany
    {
        return $this->hasMany(AssetProperty::class);
    }
}
