<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Storage;
use Spatie\Tags\HasTags;

class Directory extends Model
{
    use HasTags;

    protected $fillable = [
        'name',
        'parent_id',
    ];

    public static function getDirectoryPath(self $directory): string
    {
        $segments = [];
        $walker = $directory;
        while ($walker) {
            $segments[] = $walker->name;
            $walker = $walker->parent;
        }
        return collect($segments)->reverse()->join(DIRECTORY_SEPARATOR);
    }

    public static function processDirectoryFiles(self $directory, $action = 'update'): void
    {
        foreach ($directory->assets as $asset) {
            switch ($action) {
                case 'update':
                    Asset::updateAssetStorage($asset);
                    break;
                case 'delete':
                    $asset->delete();
                    break;
                default:
                    dd($action);
                    break;

            }
        }
    }

    public static function processDirectoryDirectories(self $directory, string $action = 'update'): void
    {
        self::processDirectoryFiles($directory, $action);
        foreach ($directory->children as $child) {
            self::processDirectoryFiles($child, $action);
            self::processDirectoryDirectories($child, $action);

            //Remove old directory.
        }
    }

    public static function deleteDirectoryChildren(self $directory): void
    {
        foreach ($directory->children as $child) {
            self::deleteDirectoryChildren($child);

            //Delete the files next
            self::processDirectoryFiles($child, 'delete');
            $child->deleteQuietly();
        }
    }

    protected static function boot(): void
    {
        static::updated(static function (self $directory) {
            if ($directory->isDirty('name')) {
                self::processDirectoryDirectories($directory);

                Storage::disk('public')
                    ->deleteDirectory(
                        \Str::of(self::getDirectoryPath($directory))
                            ->replace($directory->name, $directory->getOriginal('name'))
                    );
            }
        });

        static::deleting(static function (self $directory) {
            self::processDirectoryDirectories($directory, 'delete');
            self::deleteDirectoryChildren($directory);
        });

        static::deleted(static function (self $directory) {
            Storage::disk('public')->deleteDirectory(self::getDirectoryPath($directory));
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function parent(): BelongsTo
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function children(): HasMany
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function assets(): HasMany
    {
        return $this->hasMany(Asset::class);
    }
}
